os:
  - linux
  - linux-ppc64le
sudo: required
dist: trusty
language: scala
scala:
   - 2.12.6
   - 2.11.12
   - 2.13.0-M5
env:
- JDK=oraclejdk8
- JDK=openjdk8

matrix:
  exclude:
  - os: linux-ppc64le
    env: JDK=oraclejdk8
    
before_script:
  - jdk_switcher use $JDK
script:
- sbt "++ ${TRAVIS_SCALA_VERSION}!" test
- git diff --exit-code # check scalariform
